### ISSUE TITLE
Create Sanity Test Suite Document

### ISSUE THREAD

**Issue by b24repo** [k8-proxy-glacier/chrome-extension#11]

**Comment by kumarsudhish** [comment]
Worked on creating the test document listing out the test cases and also logged few issues.

https://docs.google.com/spreadsheets/d/1ghec5_MjzHJQxZIpk2YqBa67QdFc94tmsTSQk2fgNwg/edit#gid=0

**Comment by kumarsudhish** [comment]
Added more test cases to the suite on same sheet

https://docs.google.com/spreadsheets/d/1ghec5_MjzHJQxZIpk2YqBa67QdFc94tmsTSQk2fgNwg/edit#gid=0

**Comment by kumarsudhish** [comment]
Added test cases related to the chrome extension in the excel file.
https://docs.google.com/spreadsheets/d/1ghec5_MjzHJQxZIpk2YqBa67QdFc94tmsTSQk2fgNwg/edit#gid=1272068991
