### ISSUE TITLE
Verify the Extension

### ISSUE THREAD

**Issue by b24repo** [k8-proxy-glacier/chrome-extension#7]
Test the extension

**Comment by kumarsudhish** [comment]
Started the verification of the extension through the code and was able to test it through 3 different sample, verification of this with other sample file is still pending.
Will try to complete this by tomorrow.

**Comment by kumarsudhish** [comment]
Verified the chrome extension with different files and observed different issues in this.
Have added few issues in the sheet for discussion with the team

https://docs.google.com/spreadsheets/d/1ghec5_MjzHJQxZIpk2YqBa67QdFc94tmsTSQk2fgNwg/edit#gid=1272068991

This task is till in-progress

**Comment by kumarsudhish** [comment]
Verified the chrome extension with different files (Media files and zip files) and observed different issues in this.
Have added few issues in the sheet for discussion with the team

https://docs.google.com/spreadsheets/d/1ghec5_MjzHJQxZIpk2YqBa67QdFc94tmsTSQk2fgNwg/edit#gid=1272068991

This task is till in-progress
